---
- name: Make digikam directory.
  file:
    path: "{{ volumes_root }}/digikam"
    state: directory

- name: Get UID
  command: id -u {{ vlab_ssh_user }}
  register: uid_output

- name: Get GID
  command: id -g {{ vlab_ssh_user }}
  register: gid_output

- name: Copy digikam docker-compose.yml file into place.
  template:
    src: docker-compose.digikam.yml.j2
    dest: "{{ volumes_root }}/digikam/docker-compose.yml"
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"
    uid: "{{ uid_output.stdout }}"
    gid: "{{ gid_output.stdout }}"

- name: Configure digikam systemd service.
  become: yes
  template:
    src: service.j2
    dest: /etc/systemd/system/digikam.service

- name: Start digikam
  systemd:
    name: digikam
    enabled: yes
    daemon-reload: yes
    state: started
  become: yes
