---
- name: Make beets directory.
  file:
    path: "{{ volumes_root }}/beets"
    state: directory

- name: Get UID
  command: id -u {{ vlab_ssh_user }}
  register: uid_output

- name: Get GID
  command: id -g {{ vlab_ssh_user }}
  register: gid_output

- name: Copy beets docker-compose.yml file into place.
  template:
    src: docker-compose.beets.yml.j2
    dest: "{{ volumes_root }}/beets/docker-compose.yml"
  vars:
    tor_domain: "{{ tor_http_domain_file.stdout | default('') }}"
    uid: "{{ uid_output.stdout }}"
    gid: "{{ gid_output.stdout }}"

- name: Configure beets systemd service.
  become: yes
  template:
    src: service.j2
    dest: /etc/systemd/system/beets.service

- name: Start beets
  systemd:
    name: beets
    enabled: yes
    daemon-reload: yes
    state: started
  become: yes
