---
- name: Ensure /etc/systemd/resolved.conf.d exists
  file:
    path: /etc/systemd/resolved.conf.d
    state: directory

- name: Copy vivumlab.conf systemd resolve configuration into place.
  template:
    src: vivumlab.conf
    dest: "/etc/systemd/resolved.conf.d/vivumlab.conf"

- name: Rename standard Resolv.conf file
  command: mv /etc/resolv.conf /etc/resolv.conf.bkup

- name: link the systemd resolve file into /etc
  file:
    src: /run/systemd/resolve/resolv.conf
    dest: /etc/resolv.conf
    state: link

- name: Reload & Restart systemd-resolved
  systemd:
    name: systemd-resolved
    enabled: yes
    daemon-reload: yes
    state: restarted
  become: yes
