---
- name: Ensure Docker is not installed via Snap
  snap:
    name: docker
    state: absent
  when:
    - ansible_facts['distribution'] == 'Ubuntu'
    - ansible_facts['distribution_major_version'] is version('16.04', '>=')

- name: Remove older docker.io based packages (Ubuntu or Debian)
  apt:
    name:
      - docker
      - docker.io
      - containerd
      - runc
      - docker-engine
    state: absent
  when: (ansible_facts['distribution'] == "Ubuntu") or (ansible_facts['distribution'] == "Debian")

- name: Remove older docker.io based packages (CentOS)
  apt:
    name:
      - docker
      - docker-client
      - docker-client-latest
      - docker-common
      - docker-engine
      - docker-latest
      - docker-logrotate
      - docker-latest-logrotate
    state: absent
  when:
    - ansible_facts['distribution'] == "CentOS"

- name: Add an Apt signing key for the Docker-ce Repo (Ubuntu or Debian)
  apt_key:
    url: https://download.docker.com/linux/{{ ansible_facts['distribution'] | lower }}/gpg
    state: present
    validate_certs: no
  become: yes


- name: Add the Docker-ce Repo (Ubuntu or Debian)
  apt_repository:
    repo: deb https://download.docker.com/linux/{{ ansible_facts['distribution'] | lower }} {{ ansible_facts['distribution_release'] | lower }} stable
    state: present
  when: (ansible_facts['distribution'] == "Ubuntu") or (ansible_facts['distribution'] == "Debian")

- name: Add the Docker-ce Repo (CentOS)
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
  when:
    - ansible_facts['distribution'] == "CentOS"

- name: Install Docker and docker-compose
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - docker-compose
      - containerd.io
  tags:
    - dependencies

- name: Start Docker service
  systemd:
    state: started
    daemon_reload: yes
    name: docker
  become: yes

- name: Adding user to Docker group
  user:
    name: "{{ vlab_ssh_user }}"
    groups: docker
    append: true
  become: yes
